
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int IDENTIFIER = 75;
  public static final int BOOL = 61;
  public static final int DUMMY = 68;
  public static final int GT = 34;
  public static final int CONST = 5;
  public static final int NOTEQ = 40;
  public static final int PLUSEQ = 51;
  public static final int UNTIL = 64;
  public static final int BITWISE_OR = 48;
  public static final int RBRACK = 29;
  public static final int SIZEOF = 20;
  public static final int COMMA = 31;
  public static final int DOUBLE_LITERAL = 72;
  public static final int RBRACE = 27;
  public static final int RPAREN = 25;
  public static final int LBRACK = 28;
  public static final int LT = 35;
  public static final int DOUBLE = 8;
  public static final int LBRACE = 26;
  public static final int LPAREN = 24;
  public static final int LOGICAL_OR = 60;
  public static final int INTEGER_LITERAL = 69;
  public static final int TILDA = 59;
  public static final int FLOAT = 13;
  public static final int RECORD = 19;
  public static final int EQ = 33;
  public static final int BOOLEAN_LITERAL = 73;
  public static final int MOD = 50;
  public static final int LOGICAL_AND = 55;
  public static final int LONG = 17;
  public static final int PLUS = 41;
  public static final int LONG_LITERAL = 70;
  public static final int CHAR = 4;
  public static final int SWITCH = 22;
  public static final int FOR = 14;
  public static final int VOID = 56;
  public static final int EXTERN = 11;
  public static final int DIV = 46;
  public static final int RETURN = 18;
  public static final int MULT = 45;
  public static final int ELSE = 9;
  public static final int BREAK = 2;
  public static final int GTEQ = 39;
  public static final int DOT = 32;
  public static final int INT = 16;
  public static final int NULL_LITERAL = 23;
  public static final int STRING_LITERAL = 76;
  public static final int EQEQ = 37;
  public static final int EOF = 0;
  public static final int SEMICOLON = 30;
  public static final int DEFAULT = 7;
  public static final int FUNCTION = 12;
  public static final int MULTEQ = 53;
  public static final int REPEAT = 63;
  public static final int MINUS = 44;
  public static final int FLOAT_LITERAL = 71;
  public static final int LTEQ = 38;
  public static final int IN = 66;
  public static final int error = 1;
  public static final int DIVEQ = 54;
  public static final int CONTINUE = 6;
  public static final int IF = 15;
  public static final int MINUSMINUS = 43;
  public static final int OF = 58;
  public static final int END = 10;
  public static final int COLON = 36;
  public static final int FOREACH = 65;
  public static final int CHARACTER_LITERAL = 74;
  public static final int BEGIN = 62;
  public static final int CASE = 3;
  public static final int PLUSPLUS = 42;
  public static final int STRING = 21;
  public static final int UMINUS = 67;
  public static final int BITWISE_AND = 47;
  public static final int AUTO = 57;
  public static final int XOR = 49;
  public static final int MINUSEQ = 52;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "BREAK",
  "CASE",
  "CHAR",
  "CONST",
  "CONTINUE",
  "DEFAULT",
  "DOUBLE",
  "ELSE",
  "END",
  "EXTERN",
  "FUNCTION",
  "FLOAT",
  "FOR",
  "IF",
  "INT",
  "LONG",
  "RETURN",
  "RECORD",
  "SIZEOF",
  "STRING",
  "SWITCH",
  "NULL_LITERAL",
  "LPAREN",
  "RPAREN",
  "LBRACE",
  "RBRACE",
  "LBRACK",
  "RBRACK",
  "SEMICOLON",
  "COMMA",
  "DOT",
  "EQ",
  "GT",
  "LT",
  "COLON",
  "EQEQ",
  "LTEQ",
  "GTEQ",
  "NOTEQ",
  "PLUS",
  "PLUSPLUS",
  "MINUSMINUS",
  "MINUS",
  "MULT",
  "DIV",
  "BITWISE_AND",
  "BITWISE_OR",
  "XOR",
  "MOD",
  "PLUSEQ",
  "MINUSEQ",
  "MULTEQ",
  "DIVEQ",
  "LOGICAL_AND",
  "VOID",
  "AUTO",
  "OF",
  "TILDA",
  "LOGICAL_OR",
  "BOOL",
  "BEGIN",
  "REPEAT",
  "UNTIL",
  "FOREACH",
  "IN",
  "UMINUS",
  "DUMMY",
  "INTEGER_LITERAL",
  "LONG_LITERAL",
  "FLOAT_LITERAL",
  "DOUBLE_LITERAL",
  "BOOLEAN_LITERAL",
  "CHARACTER_LITERAL",
  "IDENTIFIER",
  "STRING_LITERAL"
  };
}

